CREATE DATABASE IF NOT EXISTS digital_bank_auth;
CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS kyc_db;
CREATE DATABASE IF NOT EXISTS banking_db;
CREATE DATABASE IF NOT EXISTS digital_bank_transaction;
CREATE DATABASE IF NOT EXISTS digital_bank_notification;
CREATE DATABASE IF NOT EXISTS audit_db;